# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SWY
brief-intro: bioinformatics
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danicalove.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: danicasun45
github_username:  danicalove
email: 1341866751@qq.com   
      

description_footer: 本站纯属胡闹

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
#duoshuo_shortname: #swyblog
disqus_shortname: danicalove

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: cf8506e0ef223e57ff6239944e5d46a4
google_analytics_id: UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6


# donate
#  reward_comment:leialeia
 # alipay:![hh](https://img3.doubanio.com/view/note/large/a8ZfBnQw7dPOOI7IEbJYDQ/147843661/x42408656.jpg)
    
 # wechatpay:![hhh](https://img1.doubanio.com/view/note/llarge/O3mA2Y8Nmg1Z0Ri9rlM06Q/147843661/x42408657.jpg)
